---
- name: Get server uptime
  hosts: all
  become: yes
  become_user: root
  connection: local
  gather_facts: False
  tasks:
    - name:  update
      apt-get:
        name:  "*"
        state: latest
#        skip_broken: yes
      #register: yum_updates
      register: apt-get update

    - name: Reboot server1
      reboot:
      when: dict((yum_updates.changes|default(dict())).updated|default([])).kernel is defined
