---
- name: Get server uptime
  hosts: all
  become: yes
  become_user: ubuntu
  gather_facts: False
  tasks:
    - name:  update
      yum:
        name:  "*"
        state: latest
#        skip_broken: yes
      register: yum_updates

    - name: Reboot server1
      reboot:
      when: dict((yum_updates.changes|default(dict())).updated|default([])).kernel is defined
